---
- name: Configure access to a private container registry
  hosts: ["control_planes", "workers"]
  become: true
  vars_files:
    - docker-credentials.yml
  tasks:
    - name: Add container registry auth info
      ansible.builtin.blockinfile:
        path: /var/snap/microk8s/current/args/containerd-template.toml
        marker: "# {mark} DOCKER.IO AUTH"  
        block: |
          [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.io".auth]
            username = "{{ username }}"
            password = "{{ password }}"
        state: present

    - name: Remove all images
      shell: microk8s ctr images rm $(microk8s ctr images list | awk 'NR>1 {print $1}')

    - name: Restart MicroK8s
      command: snap stop microk8s
      ignore_errors: true

    - name: Start MicroK8s
      command: snap start microk8s
