logger:
  file:
    path: /var/log/open5gs/open5gs.log
  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

smf:
  sbi:
    server:
      - dev:  <interface>
        port: 8005
        advertise: <host>
    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://<host>:8001
  pfcp:
    server:
      - dev:  <interface>
        advertise: <host>
    client:
      upf:
        - address: core1-node4
  gtpc:
    server:
      - dev:  <interface>
  gtpu:
    server:
      - dev:  <interface>
  metrics:
    server:
      - address: 127.0.0.4
        port: 9090
  session:
    - subnet: 10.45.0.0/24
      gateway: 10.45.0.1
      range:
        - 10.45.0.2-10.45.0.254
  dns:
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844
  mtu: 1400
#  p-cscf:
#    - 127.0.0.1
#    - ::1
#  ctf:
#    enabled: auto   # auto(default)|yes|no
  freeDiameter: /etc/freeDiameter/smf.conf
