---
- name: Remove if NAT rules are set in the head node
  become: yes
  hosts: head_node
  tasks:
    - name: Remove Forwarding Rule
      command: iptables -D FORWARD -o {{ public_interface }} -i {{ private_interface }} -s 10.123.123.0/24 -m conntrack --ctstate NEW -j ACCEPT

    - name: Remove Forwarding connection track rules
      command: iptables -D FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    - name: Remove Postrouting
      command: iptables -t nat -D POSTROUTING -o eno1 -j MASQUERADE

    - name: Disable fowarding
      command: sysctl -w net.ipv4.ip_forward=0

    - name: Persist NAT rules
      shell: mkdir -p /etc/iptables; [ -e rules.v4 ] && mv rules.v4 rules.v4.$(date +"%Y%m%d%H%M%S" ); iptables-save > /etc/iptables/rules.v4
