---
- name: Restore cointaerd defaults
  hosts: ["control_planes", "workers"]
  become: true
  tasks:
    - name: Set back the original configurations for docker.io registry
      copy:
        dest: "/var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml"
        content: |
          server = "docker.io"

          [host."https://registry-1.docker.io"]
            capabilities = ["pull", "resolve"]

    - name: Restart MicroK8s
      command: microk8s stop
      ignore_errors: true

    - name: Start MicroK8s
      command: microk8s start
